let token=localStorage.getItem("token")||"",userRole=localStorage.getItem("role")||"",briefingCache=[],selectedBriefingCategory="all",scheduleCache=[];
const pageTitles={dashboard:"Dashboard",schedule:"Training Schedule",briefingroom:"Briefing Room",weather:"Weather",aircraft:"Aircraft / G1000",modular:"Modular CPL",admin:"Admin Workspace"};
const airportCharts={LHKA:{name:"Kalocsa Airfield",chart:"https://storage.hungarocontrol.hu/media/958/VFR_LHKA_print_5n.pdf?_gl=1*1rt6n80*_gcl_au*MjQ1MTUxNTQzLjE3Nzc1NTU3MjQ."},LHJK:{name:"LHJK Airfield",chart:"https://ais-en.hungarocontrol.hu/vfrmanual/LHJK"},LHPP:{name:"LHPP Airfield",chart:"https://ais-en.hungarocontrol.hu/vfrmanual/LHPP"},LHSM:{name:"LHSM Airfield",chart:"https://ais-en.hungarocontrol.hu/vfrmanual/LHSM"}};
function toast(m){const e=document.getElementById("toast");e.textContent=m;e.classList.remove("hidden");setTimeout(()=>e.classList.add("hidden"),2800)}
function setAuthUi(){let logged=!!token;document.getElementById("loginStatus").textContent=logged?(userRole==="admin"?"Admin online":"Member online"):"Guest mode";document.getElementById("logoutBtn").classList.toggle("hidden",!logged);document.querySelector("header .primary").classList.toggle("hidden",logged);document.querySelectorAll(".admin-only").forEach(e=>e.classList.toggle("hidden",userRole!=="admin"))}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById(id).classList.add("active");document.getElementById("pageTitle").textContent=pageTitles[id]||"Avi Oren Aviation";document.querySelectorAll(".nav,.mobile-nav").forEach(b=>b.classList.toggle("active",b.dataset.page===id));if(id==="schedule")loadSchedule(false);if(id==="briefingroom")loadBriefings(false)}
document.querySelectorAll(".nav,.mobile-nav").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.page)));
function authHeaders(){return token?{"Authorization":"Bearer "+token}:{}}function openLoginModal(){document.getElementById("loginModal").classList.remove("hidden")}function closeLoginModal(){document.getElementById("loginModal").classList.add("hidden")}function logout(){localStorage.removeItem("token");localStorage.removeItem("role");token="";userRole="";setAuthUi();toast("Logged out");showPage("dashboard")}document.getElementById("logoutBtn").addEventListener("click",logout);
async function postForm(url,form){const res=await fetch(url,{method:"POST",headers:authHeaders(),body:new FormData(form)});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.detail||"Request failed");return data}
document.getElementById("loginForm").addEventListener("submit",async e=>{e.preventDefault();try{const d=await postForm("/api/login",e.target);token=d.token;userRole=d.role;localStorage.setItem("token",token);localStorage.setItem("role",userRole);setAuthUi();closeLoginModal();toast(d.approved?"Logged in":"Logged in, waiting for approval");if(userRole==="admin")showPage("admin")}catch(err){toast(err.message)}});
document.getElementById("signupForm").addEventListener("submit",async e=>{e.preventDefault();try{const d=await postForm("/api/signup",e.target);toast(d.message||"Signup created")}catch(err){toast(err.message)}});
document.getElementById("scheduleForm").addEventListener("submit",async e=>{e.preventDefault();try{await postForm("/api/schedule",e.target);e.target.reset();e.target.instructor.value="Avi Oren";toast("Flight added");loadSchedule(true)}catch(err){toast(err.message)}});
document.getElementById("studentForm").addEventListener("submit",async e=>{e.preventDefault();try{await postForm("/api/students",e.target);e.target.reset();toast("Student added")}catch(err){toast(err.message)}});
document.getElementById("briefingForm").addEventListener("submit",async e=>{e.preventDefault();try{await postForm("/api/briefings",e.target);e.target.reset();toast("File uploaded");loadBriefings(true)}catch(err){toast(err.message)}});
function formatEndTime(start,length){let [h,m]=start.split(":").map(Number),end=h*60+m+Math.round(Number(length)*60);return `${String(Math.floor(end/60)%24).padStart(2,"0")}:${String(end%60).padStart(2,"0")}`}
async function loadSchedule(showErrors=true){const empty=document.getElementById("scheduleEmpty"),tl=document.getElementById("scheduleTimeline"),res=await fetch("/api/schedule",{headers:authHeaders()}),data=await res.json().catch(()=>[]);if(!res.ok){scheduleCache=[];tl.innerHTML="";empty.classList.remove("hidden");if(showErrors)toast(data.detail||"Login required");return}scheduleCache=data;empty.classList.add("hidden");buildScheduleFilters();renderSchedule()}
function buildScheduleFilters(){const mode=document.getElementById("scheduleMode").value,sel=document.getElementById("scheduleNameFilter"),cur=sel.value;let names=[];if(mode==="fi")names=[...new Set(scheduleCache.map(r=>r.instructor))];if(mode==="student")names=[...new Set(scheduleCache.map(r=>r.student))];sel.innerHTML=`<option value="all">All</option>`+names.map(n=>`<option value="${n}">${n}</option>`).join("");if([...sel.options].some(o=>o.value===cur))sel.value=cur}
function renderSchedule(){const tl=document.getElementById("scheduleTimeline");if(!scheduleCache.length){tl.innerHTML=`<div class="empty">No flights scheduled yet.</div>`;return}const mode=document.getElementById("scheduleMode").value,date=document.getElementById("scheduleDateFilter").value,name=document.getElementById("scheduleNameFilter").value;let data=[...scheduleCache];if(date)data=data.filter(r=>r.date===date);if(name!=="all")data=data.filter(r=>mode==="fi"?r.instructor===name:mode==="student"?r.student===name:true);data.sort((a,b)=>(a.date+a.start_time).localeCompare(b.date+b.start_time));if(!data.length){tl.innerHTML=`<div class="empty">No flights match this filter.</div>`;return}let group="";tl.innerHTML=data.map(r=>{const key=mode==="daily"?r.date:mode==="fi"?r.instructor:r.student,head=key!==group?`<h3 class="timeline-group">${key}</h3>`:"";group=key;return `${head}<article class="timeline-card"><div><div class="time-block">${r.start_time}</div><div class="duration">until ${formatEndTime(r.start_time,r.length_hours)} · ${r.length_hours}h</div></div><div><div class="flight-title">${r.student}</div><div class="flight-meta"><span class="badge">${r.date}</span><span class="badge">${r.instructor}</span><span class="badge aircraft-badge">${r.aircraft_type} #${r.aircraft_number}</span></div>${r.notes?`<p>${r.notes}</p>`:""}</div><button class="ghost">Details</button></article>`}).join("")}
function selectAirport(code){document.querySelectorAll(".airport").forEach(b=>b.classList.remove("active"));[...document.querySelectorAll(".airport")].find(b=>b.innerText.includes(code))?.classList.add("active");const it=airportCharts[code];document.getElementById("selectedAirportChip").textContent=code;document.getElementById("selectedAirportName").textContent=it.name;document.getElementById("chartOpenLink").href=it.chart;document.getElementById("chartFrame").src=it.chart}
document.querySelectorAll(".tab").forEach(t=>t.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");selectedBriefingCategory=t.dataset.category;renderBriefings()}));
async function loadBriefings(showErrors=true){const empty=document.getElementById("briefingsEmpty"),grid=document.getElementById("briefingGrid"),res=await fetch("/api/briefings",{headers:authHeaders()}),data=await res.json().catch(()=>[]);if(!res.ok){briefingCache=[];grid.innerHTML="";empty.classList.remove("hidden");if(showErrors)toast(data.detail||"Login required");return}briefingCache=data;empty.classList.toggle("hidden",data.length>0);renderBriefings()}
function renderBriefings(){const grid=document.getElementById("briefingGrid"),data=selectedBriefingCategory==="all"?briefingCache:briefingCache.filter(b=>b.category===selectedBriefingCategory);if(!data.length){grid.innerHTML=`<div class="empty">No files in this category yet.</div>`;return}grid.innerHTML=data.map(b=>`<article class="file-card"><div>📄</div><a target="_blank" href="/uploads/${b.filename}">${b.title}</a><p>${b.category}</p><span class="badge">${b.original_name}</span></article>`).join("")}
function setWeatherStations(ids){document.getElementById("weatherStations").value=ids}
async function loadWeather(){const ids=document.getElementById("weatherStations").value.trim(),out=document.getElementById("weatherOutput");out.textContent="Loading public METAR/TAF data...";try{const res=await fetch(`https://aviationweather.gov/api/data/metar?ids=${encodeURIComponent(ids)}&format=raw&taf=true`);const txt=await res.text();out.textContent=txt||"No public report returned. Try different station IDs."}catch(e){out.textContent="Could not load weather in browser. Use the official HungaroMet link or aviationweather.gov directly."}}
async function loadUsers(){const res=await fetch("/api/users",{headers:authHeaders()}),data=await res.json().catch(()=>[]);if(!res.ok){toast(data.detail||"Admin login required");return}document.getElementById("usersList").innerHTML=data.map(u=>`<p><strong>${u.email}</strong><br>Role: ${u.role} · Approved: ${u.approved?"Yes":"No"}${u.approved?"":`<br><button class="ghost" onclick="approveUser('${u.id}')">Approve user</button>`}</p>`).join("")}
async function approveUser(id){const res=await fetch("/api/users/"+id+"/approve",{method:"POST",headers:authHeaders()});if(res.ok){toast("User approved");loadUsers()}else toast("Approval failed")}
setAuthUi();showPage("dashboard");