import React,{useMemo,useState}from'react';
import{Plane,CalendarDays,Users,BookOpen,Map,Link as LinkIcon,Lock,LogOut,Menu,X,GraduationCap,Phone,Settings,UserPlus,ChartNoAxesCombined}from'lucide-react';
const FI=['Avi Oren','Demo FI 2'];
const aircraft=['HA-C172D','HA-G1000'];
const demoStudents=[
{id:1,name:'Noam Levy',course:'PPL(A)',status:'Active',phone:'+972-demo',email:'noam@example.com',hours:'08:20',next:'Ex 6 - Straight & Level'},
{id:2,name:'Maya Cohen',course:'Hour Building',status:'Active',phone:'+972-demo',email:'maya@example.com',hours:'72:45',next:'Solo navigation'},
{id:3,name:'Daniel Weiss',course:'Modular CPL(A)',status:'Active',phone:'+972-demo',email:'daniel@example.com',hours:'158:10',next:'CPL nav prep'},
{id:4,name:'Eitan Bar',course:'PPL(A)',status:'Pending docs',phone:'+972-demo',email:'eitan@example.com',hours:'02:15',next:'Pre-flight briefing'},
{id:5,name:'Tamar Azulay',course:'Hour Building',status:'Active',phone:'+972-demo',email:'tamar@example.com',hours:'51:05',next:'Cross-country'},
{id:6,name:'Yoni Katz',course:'Modular CPL(A)',status:'Active',phone:'+972-demo',email:'yoni@example.com',hours:'122:30',next:'Complex airspace review'}];
const schedule=[
{day:'Monday',date:'Demo training day',slots:[['08:00','Noam Levy','Avi Oren','HA-C172D','LHKA circuits'],['10:00','Maya Cohen','Demo FI 2','HA-G1000','LHKA-LHPP-LHKA'],['13:00','Daniel Weiss','Avi Oren','HA-C172D','CPL nav briefing + flight']]},
{day:'Tuesday',date:'Demo training day',slots:[['08:30','Eitan Bar','Avi Oren','HA-G1000','First flight preparation'],['11:00','Tamar Azulay','Demo FI 2','HA-C172D','Hour building nav'],['14:00','Yoni Katz','Avi Oren','HA-G1000','CPL handling exercises']]}];
const prep=['Student onboarding and documents','ATO procedures and safety culture','Medical, license, logbook, insurance checks','First flight expectations','How to prepare for each lesson','Personal minimums and weather decision making'];
const briefings=['Effects of controls','Straight and level flight','Climbing and descending','Medium turns','Slow flight and stall awareness','Circuits and landings','Forced landing briefing','Navigation planning','G1000 cockpit scan','Threat and Error Management'];
const airports=['LHKA / LHKK - Kiskunlacháza home airfield','LHJK - Jakabszállás','LHPP - Pécs-Pogány','LHSM - Hévíz-Balaton'];
const links=[['HungaroControl AIS / AIP','https://ais-en.hungarocontrol.hu/aip/'],['Hungary VFR Manual','https://ais-en.hungarocontrol.hu/vfrmanual'],['NetBriefing Hungary','https://www.netbriefing.hu/EN/index_en.html'],['NetBriefing Airspace / LL SIGWX','https://www.netbriefing.hu/EN/airspace.html'],['Kiskunlacháza Airport official site','https://en.lhkk.hu/']];
function Login({onLogin}){return <div className="login"><div className="card loginCard"><Plane size={42}/><h1>Avi Oren Aviation</h1><p>EASA ATO training management portal for LHKA operations.</p><button onClick={()=>onLogin('member')}>Enter as member</button><button className="secondary" onClick={()=>onLogin('admin')}>Enter as admin / FI</button><small>Demo access only. Replace with real authentication before production.</small></div></div>}
function Header({page,setPage,role,setRole}){const[open,setOpen]=useState(false);const nav=['Dashboard','Preparation','Briefings','Airfields','Aircraft & G1000','Modular CPL','Schedule','Students','Useful Links','Contact'];return <><header><div className="brand" onClick={()=>setPage('Dashboard')}><Plane/><span>Avi Oren Aviation</span></div><button className="icon" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'show':''}>{nav.map(n=><button key={n} className={page===n?'active':''} onClick={()=>{setPage(n);setOpen(false)}}>{n}</button>)}<button onClick={()=>setRole(null)}><LogOut size={16}/> Logout</button></nav></header><div className="role">Logged in as <b>{role}</b> · Member-only briefing portal demo</div></>}
function Gate({role,children}){return role?<>{children}</>:<div className="locked"><Lock/> Members only</div>}
function Dashboard(){return <main><section className="hero"><div><h1>Training portal for Israeli trainees in Hungary</h1><p>PPL(A), hour building, and modular CPL(A) support at LHKA using diesel C172 aircraft equipped with Garmin G1000.</p><div className="chips"><span>EASA ATO</span><span>LHKA / LHKK</span><span>C172 Diesel</span><span>G1000</span></div></div><Plane size={90}/></section><div className="grid"><Card icon={<BookOpen/>} title="Briefings">Central access to lesson presentations, airport briefings, aircraft information, charts links, and preparation tasks.</Card><Card icon={<CalendarDays/>} title="Schedule">Demo schedule for 6 students, 2 FIs, and 2 aircraft. Replace with your live training plan later.</Card><Card icon={<Users/>} title="Students">Admin screen for student status, course type, hours, contact details, and next training item.</Card></div></main>}
function Card({icon,title,children}){return <div className="card">{icon}<h3>{title}</h3><p>{children}</p></div>}
function ListPage({title,items,icon}){return <main><h1>{icon} {title}</h1><div className="list">{items.map((x,i)=><div className="row" key={x}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span><button>Open</button></div>)}</div></main>}
function Airfields(){return <main><h1><Map/> Airfields & charts briefing</h1><p className="notice">Operational charts should be opened from the current official AIP / VFR Manual before each flight. This portal links to the source instead of storing stale charts.</p><div className="grid">{airports.map(a=><Card key={a} icon={<Map/>} title={a}>Briefing template: runway data, circuit direction, joining procedures, local threats, noise abatement, fuel/handling, alternates, and latest NOTAM/charts check.</Card>)}</div></main>}
function Aircraft(){return <main><h1><ChartNoAxesCombined/> Aircraft, G1000 & flight data</h1><div className="grid"><Card icon={<Plane/>} title="C172 Diesel">Normal/abnormal procedures, fuel system, engine indications, limitations, mass & balance, performance and checklist discipline.</Card><Card icon={<Settings/>} title="Garmin G1000">PFD/MFD layout, flight plan entry, map range, nearest pages, transponder, alerts, engine page, and failure modes.</Card><Card icon={<BookOpen/>} title="Flight data reading">How to review track, altitude, speed, engine trends, circuit profile and student debriefing points.</Card></div></main>}
function Modular(){return <main><h1><GraduationCap/> Modular training course</h1><div className="card"><h3>Modular CPL(A) overview</h3><p>Use this page for your ATO-specific syllabus, EASA references, hour requirements, prerequisites, night/IR/MCC integration notes, and checkride preparation flow.</p><ul><li>Student entry requirements and documents</li><li>Hour-building tracking</li><li>CPL navigation and general handling standards</li><li>ATO progress checks and readiness gates</li></ul></div></main>}
function Schedule(){return <main><h1><CalendarDays/> Schedule</h1>{schedule.map(d=><section className="card" key={d.day}><h2>{d.day} · {d.date}</h2><table><thead><tr><th>Time</th><th>Student</th><th>FI</th><th>Aircraft</th><th>Plan</th></tr></thead><tbody>{d.slots.map((s,i)=><tr key={i}>{s.map(v=><td key={v}>{v}</td>)}</tr>)}</tbody></table></section>)}</main>}
function Students({role}){const[students,setStudents]=useState(demoStudents);const[name,setName]=useState('');function add(){if(!name.trim())return;setStudents([...students,{id:Date.now(),name,course:'PPL(A)',status:'New',phone:'',email:'',hours:'00:00',next:'Onboarding'}]);setName('')}return <main><h1><Users/> Students & users</h1>{role==='admin'&&<div className="adminbar"><input value={name} onChange={e=>setName(e.target.value)} placeholder="New student name"/><button onClick={add}><UserPlus size={16}/> Add student</button></div>}<table><thead><tr><th>Name</th><th>Course</th><th>Status</th><th>Hours</th><th>Next</th><th>Email</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.course}</td><td>{s.status}</td><td>{s.hours}</td><td>{s.next}</td><td>{s.email}</td></tr>)}</tbody></table></main>}
function Useful(){return <main><h1><LinkIcon/> Useful links</h1><div className="list">{links.map(([t,u])=><a className="row" href={u} target="_blank"><b><LinkIcon size={18}/></b><span>{t}</span><button>Open</button></a>)}</div></main>}
function Contact(){return <main><h1><Phone/> Contact</h1><div className="card"><h2>Avi Oren Aviation</h2><p>Training coordination, flight scheduling, briefing access and student support.</p><p><b>Email:</b> add-your-email@example.com</p><p><b>Phone:</b> add your phone</p><p><b>Base:</b> LHKA / Kiskunlacháza area, Hungary</p></div></main>}
export default function App(){const[role,setRole]=useState(null);const[page,setPage]=useState('Dashboard');const component=useMemo(()=>({Dashboard:<Dashboard/>,Preparation:<Gate role={role}><ListPage title="Preparation before first flying" icon={<BookOpen/>} items={prep}/></Gate>,Briefings:<Gate role={role}><ListPage title="Training exercise briefings" icon={<BookOpen/>} items={briefings}/></Gate>,Airfields:<Gate role={role}><Airfields/></Gate>,'Aircraft & G1000':<Gate role={role}><Aircraft/></Gate>,'Modular CPL':<Gate role={role}><Modular/></Gate>,Schedule:<Schedule/>,Students:<Gate role={role}><Students role={role}/></Gate>,'Useful Links':<Useful/>,Contact:<Contact/>}),[role]);if(!role)return <Login onLogin={setRole}/>;return <><Header page={page} setPage={setPage} role={role} setRole={setRole}/>{component[page]}</>}
